name: Linters

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        bun-version: [1.0.0]
    timeout-minutes: 20
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: ESLint with bun
        run: bun run lint

      - name: Stylelint with bun
        run: bun run stylelint

  # eslint:
  #   name: ESLint
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '18.x'
  #     - name: Setup ESLint
  #       run: |
  #         npm install --save-dev eslint@8.45.0 eslint-plugin-react-hooks@4.6.0 eslint-plugin-react-refresh@0.4.3 @typescript-eslint/eslint-plugin@^6.0.0 @typescript-eslint/parser@^6.0.0
  #         [ -f .eslintrc.cjs ] || cp .eslintrc.cjs.example .eslintrc.cjs
  #     - name: ESLint Report
  #       run: npx eslint .
  # stylelint:
  #   name: Stylelint
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '18.x'
  #     - name: Setup Stylelint
  #       run: |
  #         npm install --save-dev stylelint@15.10.0 stylelint-config-recommended@13.0.0 stylelint-order@6.0.3
  #         [ -f .stylelintrc.json ] || cp .stylelintrc.json.example .stylelintrc.json
  #     - name: Stylelint Report
  #       run: npx stylelint "**/*.{css,scss}"
