name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup ESLint
        run: npm install --save-dev eslint@8.45.0 eslint-plugin-react-hooks@4.6.0 eslint-plugin-react-refresh@0.4.3 @typescript-eslint/eslint-plugin@^6.0.0 @typescript-eslint/parser@^6.0.0
      - name: ESLint Report
        run: npx eslint .
  stylelint:
    name: Stylelint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
          [ -f .stylelintrc.json ] || cp .stylelintrc.json.example .stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"
