name: CI

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  Linters:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        bun-version: [1.0.0]
    timeout-minutes: 20
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: ESLint with bun
        run: bun run lint

      - name: Stylelint with bun
        run: bun run stylelint
